--CREATE TABLE Users(
--id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--FirstName NVARCHAR(100) NOT NULL,
--LastName NVARCHAR(100),
--GoogleID NVARCHAR(255) NOT NULL
--);


--SELECT * FROM Users;

--DELETE FROM Users
--WHERE id = 1;